apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-myfirst
  labels:
    testing.upbound.io/example-name: rg-myfirst
spec:
  forProvider:
    location: West US3
    tags:
      provisioner: crossplane      
---
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  annotations:
    meta.upbound.io/example-id: containerservice/v1beta1/kubernetesclusterextension
  labels:
    testing.upbound.io/example-name: rg-myfirst
  name: test-clu1
spec:
  forProvider:
    apiServerAccessProfile:
      - authorizedIpRanges:
          - 82.9.176.134/32
          - 4.166.45.168/32
    defaultNodePool:
      - name: default
        nodeCount: 1
        autoScalingEnabled: true
        maxCount: 5
        minCount: 1
        vmSize: Standard_D2_v2
    dnsPrefix: exampleaks1se
    identity:
      - type: SystemAssigned
    oidcIssuerEnabled: true
    workloadIdentityEnabled: true
    keyVaultSecretsProvider:
      - secretRotationEnabled: true
    location: Sweden Central
    azurePolicyEnabled: true
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: rg-myfirst
    tags:
      Environment: Test
      Owner: Ore
  writeConnectionSecretToRef:
    name: test-clu1-secret
    namespace: crossplane-system
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-kubernetes:v1.0.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-helm:v1.2.5
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: clu1-prov-helm
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  credentials:
    source: Secret
    secretRef:
      name: test-clu1-secret
      namespace: crossplane-system
      key: kubeconfig
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: clu1-prov-k8s
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  credentials:
    source: Secret
    secretRef:
      name: test-clu1-secret
      namespace: crossplane-system
      key: kubeconfig
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    crossplane.io/external-name: argocd
  name: clu1-argo  
spec:
  forProvider:
    chart:
      name: argo-cd
      repository: https://argoproj.github.io/argo-helm
      version:  9.5.20
    namespace: argocd   
    values:
      controller:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      applicationSet:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      notifications:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      server:
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      repoServer:
        copyutil:
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      dex:
        initImage:
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      redis:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      redisSecretInit:
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
  providerConfigRef: 
    name: clu1-prov-helm
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: core-cluster-configs
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    manifest:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: core-cluster-configs
        namespace: argocd
        finalizers:
        - resources-finalizer.argocd.argoproj.io
      spec:
        project: default
        source:    
          repoURL: "https://github.com/oreakinodidi98/PlatformEngineeringDemo" # Use your repo
          targetRevision: HEAD
          path: "workloads/team01"
        syncPolicy:
            automated: {}
        destination:
            namespace: argocd
            server: https://kubernetes.default.svc
  providerConfigRef: 
    name: clu1-prov-k8s
