apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  namespace: {{ .Values.namespace.name }}
data:
  KEYVAULT_NAME: {{ .Values.scrprovclass.keyVaultname | quote }}
  TENANT_ID: {{ .Values.scrprovclass.tenantId | quote }}
