apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-demo
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-demo
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: busybox
          image: mcr.microsoft.com/oss/busybox/busybox:1.35
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
