apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: {{ .Values.namespace.name }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceaccount.clientId | quote }}
  labels:
    azure.workload.identity/use: "true"
