apiVersion: compute.example.com/v1alpha1
kind: staging-aks
metadata:
  name: my56app
spec: 
  clustername: my56cluster
  teamname: team01
  location: EU
  repourl: https://github.com/oreakinodidi98/PlatformEngineeringDemo
  repopath: workloads/team01
